global:
  scrape_interval: 2s # Default is every 1 minute.
  evaluation_interval: 2s # The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'prometheus-demo'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "/etc/prometheus/rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"
    # scheme defaults to 'http'.
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "alertmanager"
    static_configs:
      - targets: ["alertmanager:9093"]

  - job_name: "blackbox_exporter"
    static_configs:
      - targets: ["blackbox_exporter:9115"]

  - job_name: "grafana"
    static_configs:
      - targets: ["grafana:3000"]

  # This example requires Docker daemon to be configured to expose
  # Prometheus metrics, as documented here:
  # https://docs.docker.com/config/daemon/prometheus/
  - job_name: "docker-daemon"
    static_configs:
      - targets: ["host.docker.internal:9323"]

  # See more labels:
  # https://prometheus.io/docs/prometheus/latest/configuration/configuration/#docker_sd_config
  - job_name: "docker-containers"
    docker_sd_configs:
      - host: unix:///var/run/docker.sock # You can also use http/https to connect to the Docker daemon.
        filters:
         - name: label
           values: ["app=webserver"]
        refresh_interval: 2s

  - job_name: "ping"
    docker_sd_configs:
      - host: unix:///var/run/docker.sock # You can also use http/https to connect to the Docker daemon.
        filters:
         - name: label
           values: ["app=webserver"]
        refresh_interval: 2s
    metrics_path: /probe
    params:
      module: [icmp]  # Look for a HTTP 200 response.
    relabel_configs:
      - source_labels: [__meta_docker_container_label_com_docker_compose_service]
        target_label: container_service
      - source_labels: [__meta_docker_container_name]
        target_label: container_name 
      - source_labels: [__meta_docker_network_ip]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115  # The blackbox exporter's real hostname:port.
